//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClientPlanPensiones.WebReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deduct", ReplyAction="http://tempuri.org/IService1/DeductResponse")]
        double Deduct(double companyPensionPlan, double personPensionPlan, double taxBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Deduct", ReplyAction="http://tempuri.org/IService1/DeductResponse")]
        System.Threading.Tasks.Task<double> DeductAsync(double companyPensionPlan, double personPensionPlan, double taxBase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BitcoinInvestment", ReplyAction="http://tempuri.org/IService1/BitcoinInvestmentResponse")]
        double[] BitcoinInvestment(double[] savings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BitcoinInvestment", ReplyAction="http://tempuri.org/IService1/BitcoinInvestmentResponse")]
        System.Threading.Tasks.Task<double[]> BitcoinInvestmentAsync(double[] savings);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfClientPlanPensiones.WebReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfClientPlanPensiones.WebReference.IService1>, WcfClientPlanPensiones.WebReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double Deduct(double companyPensionPlan, double personPensionPlan, double taxBase) {
            return base.Channel.Deduct(companyPensionPlan, personPensionPlan, taxBase);
        }
        
        public System.Threading.Tasks.Task<double> DeductAsync(double companyPensionPlan, double personPensionPlan, double taxBase) {
            return base.Channel.DeductAsync(companyPensionPlan, personPensionPlan, taxBase);
        }
        
        public double[] BitcoinInvestment(double[] savings) {
            return base.Channel.BitcoinInvestment(savings);
        }
        
        public System.Threading.Tasks.Task<double[]> BitcoinInvestmentAsync(double[] savings) {
            return base.Channel.BitcoinInvestmentAsync(savings);
        }
    }
}
